
version: '3.8'

services:
  genesis-mysql:
    image: mysql:8.0
    container_name: genesis-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: genesis
      MYSQL_USER: empire
      MYSQL_PASSWORD: empirepass
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

